import Head from "next/head";
import axios from "axios";
import { css } from "@emotion/react";

// types
import type { GetServerSideProps } from "next";
import type { GetIdResponseData } from "types/open-api";

interface Props {
  nickname: string;
}

interface Params {
  [key: string]: string;
  nickname: string;
}

const Page = ({ nickname }: Props) => {
  return (
    <>
      <Head>
        <title>{nickname}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div
        css={css`
          background: blue;
        `}
      >
        hello world
      </div>
    </>
  );
};

export const getServerSideProps: GetServerSideProps<Props, Params> = async ({
  params,
}) => {
  try {
    if (params?.nickname) {
      const {
        data: { ocid },
      } = await axios.get<GetIdResponseData>(
        `/api/id?nickname=${params.nickname}`
      );

      return {
        props: { nickname: params.nickname },
      };
    }

    return {
      props: { nickname: "ERROR" },
    };
  } catch (err) {
    return {
      props: { nickname: "ERROR" },
    };
  }
};

export default Page;
