import Head from "next/head";
import { css } from "@emotion/react";

const Index = () => {
  return (
    <>
      <Head>
        <title>솔킹</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <div
        css={css`
          background: red;
        `}
      >
        hello world
      </div>
    </>
  );
};

export default Index;
